-- PAUTA DOCENTE: PRUEBA PRACTICA DE REFUERZO - UNIDAD 1
-- Caso: reportería de Recursos Humanos sobre el modelo OEHR
-- Las soluciones equivalentes que entreguen la información solicitada también son válidas.

-- =============================================================================
-- TEMA 1: SELECT, EXPRESIONES, ALIAS, CONCATENACION Y DISTINCT
-- =============================================================================

-- Pregunta 1
SELECT *
FROM OEHR_DEPARTMENTS;

-- Pregunta 2
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       FIRST_NAME AS "NOMBRE",
       LAST_NAME AS "APELLIDO",
       SALARY AS "SUELDO"
FROM OEHR_EMPLOYEES;

-- Pregunta 3
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       SALARY AS "SUELDO_MENSUAL",
       SALARY * 12 AS "SUELDO_ANUAL",
       (SALARY + 75) * 12 AS "SUELDO_ANUAL_CON_BONO"
FROM OEHR_EMPLOYEES;

-- Pregunta 4
SELECT 'EL EMPLEADO ' || FIRST_NAME || ' ' || LAST_NAME ||
       ' TIENE COMO CARGO ' || JOB_ID AS "REPORTE"
FROM OEHR_EMPLOYEES;

-- Pregunta 5
SELECT DISTINCT JOB_ID AS "CARGOS_VIGENTES"
FROM OEHR_EMPLOYEES;

-- Pregunta 6
SELECT JOB_ID AS "COD_CARGO",
       JOB_TITLE AS "NOMBRE_CARGO",
       MIN_SALARY AS "SUELDO_MINIMO",
       MAX_SALARY AS "SUELDO_MAXIMO",
       MAX_SALARY - MIN_SALARY AS "RANGO_SALARIAL"
FROM OEHR_JOBS;

-- =============================================================================
-- TEMA 2: RESTRICCION, OPERADORES, PATRONES, NULOS Y ORDENAMIENTO
-- =============================================================================

-- Pregunta 7
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       SALARY AS "SUELDO",
       DEPARTMENT_ID AS "COD_DEPARTAMENTO"
FROM OEHR_EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000
  AND DEPARTMENT_ID IN (50, 80)
ORDER BY SALARY DESC, LAST_NAME ASC;

-- Pregunta 8
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       HIRE_DATE AS "FECHA_CONTRATACION",
       COMMISSION_PCT AS "COMISION"
FROM OEHR_EMPLOYEES
WHERE HIRE_DATE >= DATE '2015-01-01'
  AND COMMISSION_PCT IS NULL
ORDER BY HIRE_DATE ASC;

-- Pregunta 9
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       FIRST_NAME AS "NOMBRE",
       LAST_NAME AS "APELLIDO"
FROM OEHR_EMPLOYEES
WHERE UPPER(LAST_NAME) LIKE 'S%'
   OR UPPER(LAST_NAME) LIKE '%N';

-- Pregunta 10
SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO",
       DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_DEPARTMENTS
WHERE DEPARTMENT_ID IN (10, 50, 90)
ORDER BY DEPARTMENT_NAME ASC;

-- Pregunta 11
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       JOB_ID AS "CARGO",
       MANAGER_ID AS "COD_JEFE"
FROM OEHR_EMPLOYEES
WHERE JOB_ID NOT IN ('AD_PRES', 'AD_VP', 'SA_MAN')
  AND MANAGER_ID IS NOT NULL;

-- Pregunta 12
SELECT *
FROM OEHR_DEPARTMENTS
WHERE UPPER(DEPARTMENT_NAME) LIKE '_A%S';

-- =============================================================================
-- TEMA 3: FUNCIONES DE TEXTO, NUMERO Y FECHA
-- =============================================================================

-- Pregunta 13
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       UPPER(FIRST_NAME || ' ' || LAST_NAME) AS "NOMBRE_COMPLETO",
       LOWER(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;

-- Pregunta 14
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LOWER(SUBSTR(FIRST_NAME, 1, 1) || LAST_NAME || '@rrhh.cl') AS "NUEVO_EMAIL"
FROM OEHR_EMPLOYEES;

-- Pregunta 15
SELECT LAST_NAME AS "APELLIDO",
       LENGTH(LAST_NAME) AS "LARGO_APELLIDO",
       SUBSTR(JOB_ID, 1, 3) AS "AREA_CARGO"
FROM OEHR_EMPLOYEES;

-- Pregunta 16
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       FIRST_NAME || ' ' || LAST_NAME AS "NOMBRE_COMPLETO",
       HIRE_DATE AS "FECHA_CONTRATACION",
       TRUNC((SYSDATE - HIRE_DATE) / 7) AS "SEMANAS_TRABAJADAS"
FROM OEHR_EMPLOYEES
ORDER BY "SEMANAS_TRABAJADAS" ASC;

-- Pregunta 17
SELECT SALARY AS "SUELDO",
       ROUND(SALARY / 7, 2) AS "CUOTA_REDONDEADA",
       MOD(TRUNC(SALARY), 7) AS "RESTO_DIVISION"
FROM OEHR_EMPLOYEES;

-- Pregunta 18
SELECT EMAIL AS "EMAIL_ORIGINAL",
       SUBSTR(EMAIL, 1, LENGTH(EMAIL) - 2) ||
       SUBSTR(EMAIL, LENGTH(EMAIL), 1) || '@sql.cl' AS "EMAIL_PROPUESTO"
FROM OEHR_EMPLOYEES;

-- =============================================================================
-- TEMA 4: CONVERSION, FORMATO, FECHAS Y TRATAMIENTO DE NULOS
-- =============================================================================

-- Pregunta 19
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       TO_CHAR(SALARY, 'FM$999G999G990D00',
               'NLS_NUMERIC_CHARACTERS=''.,''') AS "SUELDO_FORMATO"
FROM OEHR_EMPLOYEES;

-- Pregunta 20
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       UPPER(TO_CHAR(HIRE_DATE, 'DD "DE" FMMonth "DE" YYYY',
                     'NLS_DATE_LANGUAGE=SPANISH')) AS "FECHA_CONTRATO"
FROM OEHR_EMPLOYEES;

-- Pregunta 21
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       TO_CHAR(NVL(COMMISSION_PCT, 0) * 100, 'FM990D00') || '%' AS "COMISION"
FROM OEHR_EMPLOYEES;

-- Pregunta 22
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       NVL2(COMMISSION_PCT, 'CON COMISION', 'SIN COMISION') AS "ESTADO_COMISION"
FROM OEHR_EMPLOYEES;

-- Pregunta 23
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       TO_NUMBER(TO_CHAR(HIRE_DATE, 'YYYY'), '9999') AS "ANIO_CONTRATACION"
FROM OEHR_EMPLOYEES
WHERE TO_NUMBER(TO_CHAR(HIRE_DATE, 'YYYY'), '9999') > 2015
ORDER BY "ANIO_CONTRATACION" DESC;

-- Pregunta 24
SELECT EMPLOYEE_ID AS "COD_EMPLEADO",
       LAST_NAME AS "APELLIDO",
       SALARY AS "SUELDO",
       CASE
           WHEN SALARY >= 10000 THEN 'TRAMO ALTO'
           WHEN SALARY >= 5000 THEN 'TRAMO MEDIO'
           ELSE 'TRAMO BAJO'
       END AS "TRAMO_SALARIAL"
FROM OEHR_EMPLOYEES;

-- =============================================================================
-- TEMA 5: FUNCIONES DE GRUPO, GROUP BY Y HAVING
-- =============================================================================

-- Pregunta 25
SELECT ROUND(AVG(SALARY), 0) AS "PROMEDIO",
       MIN(SALARY) AS "MINIMO",
       MAX(SALARY) AS "MAXIMO"
FROM OEHR_EMPLOYEES;

-- Pregunta 26
SELECT COUNT(DISTINCT DEPARTMENT_ID) AS "DEPARTAMENTOS_CON_EMPLEADOS"
FROM OEHR_EMPLOYEES;

-- Pregunta 27
SELECT JOB_ID AS "CARGO",
       COUNT(EMPLOYEE_ID) AS "CANTIDAD_EMPLEADOS",
       ROUND(AVG(SALARY), 0) AS "PROMEDIO_SUELDOS",
       MAX(SALARY) - MIN(SALARY) AS "DIFERENCIA_SUELDOS"
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID
HAVING MAX(SALARY) - MIN(SALARY) <> 0;

-- Pregunta 28
SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO",
       JOB_ID AS "CARGO",
       TO_CHAR(SUM(SALARY), 'FM$999G999G990D00',
               'NLS_NUMERIC_CHARACTERS=''.,''') AS "TOTAL_SUELDOS"
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 100
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;

-- Pregunta 29
SELECT DEPARTMENT_ID AS "COD_DEPARTAMENTO",
       ROUND(AVG(SALARY), 0) AS "PROMEDIO_SUELDOS"
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000
ORDER BY "PROMEDIO_SUELDOS" DESC;

-- Pregunta 30
SELECT JOB_ID AS "CARGO",
       COUNT(EMPLOYEE_ID) AS "TOTAL_EMPLEADOS",
       COUNT(COMMISSION_PCT) AS "EMPLEADOS_CON_COMISION"
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(EMPLOYEE_ID) >= 2;

-- =============================================================================
-- TEMA 6: JOIN, CLAVES FORANEAS, AUTORRELACIONES Y SUBCONSULTAS
-- =============================================================================

-- Pregunta 31
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO",
       E.FIRST_NAME || ' ' || E.LAST_NAME AS "NOMBRE_EMPLEADO",
       J.JOB_TITLE AS "CARGO",
       D.DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J
  ON E.JOB_ID = J.JOB_ID
JOIN OEHR_DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- Pregunta 32
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO",
       E.LAST_NAME AS "APELLIDO",
       L.CITY AS "CIUDAD",
       C.COUNTRY_NAME AS "PAIS",
       R.REGION_NAME AS "REGION"
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_LOCATIONS L
  ON D.LOCATION_ID = L.LOCATION_ID
JOIN OEHR_COUNTRIES C
  ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN OEHR_REGIONS R
  ON C.REGION_ID = R.REGION_ID;

-- Pregunta 33
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO",
       E.FIRST_NAME || ' ' || E.LAST_NAME AS "EMPLEADO",
       M.FIRST_NAME || ' ' || M.LAST_NAME AS "JEFE_DIRECTO"
FROM OEHR_EMPLOYEES E
LEFT JOIN OEHR_EMPLOYEES M
  ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- Pregunta 34
SELECT D.DEPARTMENT_ID AS "COD_DEPARTAMENTO",
       D.DEPARTMENT_NAME AS "DEPARTAMENTO",
       M.FIRST_NAME || ' ' || M.LAST_NAME AS "JEFE_DEPARTAMENTO"
FROM OEHR_DEPARTMENTS D
LEFT JOIN OEHR_EMPLOYEES M
  ON D.MANAGER_ID = M.EMPLOYEE_ID;

-- Pregunta 35
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO",
       E.LAST_NAME AS "APELLIDO",
       H.START_DATE AS "FECHA_INICIO",
       H.END_DATE AS "FECHA_TERMINO",
       J.JOB_TITLE AS "CARGO_HISTORICO",
       D.DEPARTMENT_NAME AS "DEPARTAMENTO_HISTORICO"
FROM OEHR_JOB_HISTORY H
JOIN OEHR_EMPLOYEES E
  ON H.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN OEHR_JOBS J
  ON H.JOB_ID = J.JOB_ID
LEFT JOIN OEHR_DEPARTMENTS D
  ON H.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- Pregunta 36
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO",
       E.FIRST_NAME || ' ' || E.LAST_NAME AS "NOMBRE_EMPLEADO",
       D.DEPARTMENT_NAME AS "DEPARTAMENTO",
       J.JOB_TITLE AS "CARGO",
       E.COMMISSION_PCT AS "COMISION"
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_JOBS J
  ON E.JOB_ID = J.JOB_ID
WHERE E.DEPARTMENT_ID IN (
          SELECT DEPARTMENT_ID
          FROM OEHR_EMPLOYEES
          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING')
      )
  AND E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME;

