-- PAUTA DOCENTE: PRUEBA PRACTICA INTENSIVA U1
-- Modelo OEHR. Se aceptan soluciones equivalentes que produzcan el resultado pedido.

-- Pregunta 1
SELECT JOB_ID AS COD_CARGO,
       JOB_TITLE AS NOMBRE_CARGO,
       MIN_SALARY AS SUELDO_MINIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_ID) LIKE 'S%';

-- Pregunta 2
SELECT JOB_ID AS COD_CARGO,
       JOB_TITLE AS NOMBRE_CARGO,
       MIN_SALARY AS SUELDO_MINIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_TITLE) LIKE 'S%';

-- Pregunta 3
SELECT 'El cargo ' || JOB_TITLE || ' tiene el codigo ' || JOB_ID AS REPORTE,
       MIN_SALARY AS SUELDO_MINIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_ID) LIKE 'A%'
   OR UPPER(JOB_TITLE) LIKE 'A%';

-- Pregunta 4
SELECT JOB_ID || ' corresponde a ' || JOB_TITLE AS CARGO,
       MIN_SALARY AS SUELDO_MINIMO,
       MAX_SALARY AS SUELDO_MAXIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_TITLE) LIKE '%MANAGER%';

-- Pregunta 5
SELECT JOB_ID || ' - ' || JOB_TITLE AS CARGO,
       MIN_SALARY AS SUELDO_MINIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_ID) LIKE '_A%'
   OR UPPER(JOB_TITLE) LIKE '%CLERK';

-- Pregunta 6
SELECT 'El codigo del cargo ' || JOB_TITLE || ' es: ' || JOB_ID AS REPORTE,
       MIN_SALARY AS SUELDO_MINIMO
FROM OEHR_JOBS
WHERE UPPER(JOB_ID) LIKE 'S%'
   OR UPPER(JOB_TITLE) LIKE 'S%'
ORDER BY MIN_SALARY DESC, JOB_TITLE;

-- Pregunta 7
SELECT J.JOB_ID AS COD_CARGO,
       J.JOB_TITLE AS NOMBRE_CARGO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_JOBS J
JOIN OEHR_EMPLOYEES E ON E.JOB_ID = J.JOB_ID
WHERE UPPER(J.JOB_ID) LIKE 'S%'
   OR UPPER(J.JOB_TITLE) LIKE 'S%'
GROUP BY J.JOB_ID, J.JOB_TITLE
HAVING COUNT(E.EMPLOYEE_ID) >= 2;

-- Pregunta 8
SELECT J.JOB_ID AS COD_CARGO,
       J.JOB_TITLE AS NOMBRE_CARGO,
       J.MIN_SALARY AS MINIMO_DEFINIDO,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL
FROM OEHR_JOBS J
JOIN OEHR_EMPLOYEES E ON E.JOB_ID = J.JOB_ID
WHERE UPPER(J.JOB_ID) LIKE 'S%'
   OR UPPER(J.JOB_TITLE) LIKE 'S%'
GROUP BY J.JOB_ID, J.JOB_TITLE, J.MIN_SALARY
HAVING AVG(E.SALARY) > J.MIN_SALARY
ORDER BY AVG(E.SALARY) DESC;

-- Pregunta 9
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE UPPER(J.JOB_ID) LIKE 'S%'
   OR UPPER(J.JOB_TITLE) LIKE 'S%'
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 2;

-- Pregunta 10
SELECT R.REGION_NAME AS REGION,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       COUNT(DISTINCT J.JOB_ID) AS CARGOS_DISTINTOS
FROM OEHR_REGIONS R
JOIN OEHR_COUNTRIES C ON C.REGION_ID = R.REGION_ID
JOIN OEHR_LOCATIONS L ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN OEHR_DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE UPPER(J.JOB_ID) LIKE 'S%'
   OR UPPER(J.JOB_TITLE) LIKE 'S%'
GROUP BY R.REGION_NAME
HAVING COUNT(E.EMPLOYEE_ID) > 1;

-- Pregunta 11
SELECT JOB_ID AS CARGO,
       COUNT(EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID;

-- Pregunta 12
SELECT JOB_ID AS CARGO,
       ROUND(AVG(SALARY), 0) AS SUELDO_PROMEDIO,
       MIN(SALARY) AS SUELDO_MINIMO,
       MAX(SALARY) AS SUELDO_MAXIMO
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID;

-- Pregunta 13
SELECT JOB_ID AS CARGO,
       COUNT(EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(SALARY), 0) AS SUELDO_PROMEDIO,
       MAX(SALARY) - MIN(SALARY) AS DIFERENCIA_SUELDOS
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID
HAVING MAX(SALARY) - MIN(SALARY) <> 0;

-- Pregunta 14
SELECT DEPARTMENT_ID AS COD_DEPARTAMENTO,
       COUNT(EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       SUM(SALARY) AS TOTAL_SUELDOS
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
ORDER BY SUM(SALARY) DESC;

-- Pregunta 15
SELECT JOB_ID AS CARGO,
       COUNT(EMPLOYEE_ID) AS TOTAL_EMPLEADOS,
       COUNT(COMMISSION_PCT) AS EMPLEADOS_CON_COMISION
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(EMPLOYEE_ID) >= 2;

-- Pregunta 16
SELECT DEPARTMENT_ID AS COD_DEPARTAMENTO,
       JOB_ID AS CARGO,
       COUNT(EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(SALARY), 0) AS SUELDO_PROMEDIO,
       MAX(SALARY) - MIN(SALARY) AS DIFERENCIA_SUELDOS
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 50 AND 100
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING MAX(SALARY) - MIN(SALARY) > 1000;

-- Pregunta 17
SELECT J.JOB_ID AS COD_CARGO,
       J.JOB_TITLE AS NOMBRE_CARGO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL,
       J.MIN_SALARY AS MINIMO_DEFINIDO
FROM OEHR_JOBS J
JOIN OEHR_EMPLOYEES E ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID, J.JOB_TITLE, J.MIN_SALARY
HAVING AVG(E.SALARY) > J.MIN_SALARY
   AND COUNT(E.EMPLOYEE_ID) >= 2;

-- Pregunta 18
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, M.FIRST_NAME, M.LAST_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 3
   AND AVG(E.SALARY) > 5000;

-- Pregunta 19
SELECT R.REGION_NAME AS REGION,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO,
       MAX(E.SALARY) - MIN(E.SALARY) AS DIFERENCIA_SUELDOS
FROM OEHR_REGIONS R
JOIN OEHR_COUNTRIES C ON C.REGION_ID = R.REGION_ID
JOIN OEHR_LOCATIONS L ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN OEHR_DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY R.REGION_NAME
HAVING MAX(E.SALARY) - MIN(E.SALARY) > 5000;

-- Pregunta 20
SELECT JOB_ID AS CARGO,
       COUNT(EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(SALARY), 0) AS PROMEDIO_CARGO,
       ROUND((SELECT AVG(SALARY) FROM OEHR_EMPLOYEES), 0) AS PROMEDIO_GENERAL
FROM OEHR_EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > (SELECT AVG(SALARY) FROM OEHR_EMPLOYEES)
ORDER BY AVG(SALARY) DESC;

-- Pregunta 21
SELECT E.EMPLOYEE_ID AS CODIGO_TRABAJADOR,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE_TRABAJADOR,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DEPARTAMENTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID;

-- Pregunta 22
SELECT E.EMPLOYEE_ID AS CODIGO_TRABAJADOR,
       E.LAST_NAME AS APELLIDO_TRABAJADOR,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.LAST_NAME AS APELLIDO_JEFE
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
WHERE D.DEPARTMENT_ID BETWEEN 30 AND 90
ORDER BY D.DEPARTMENT_ID, E.LAST_NAME;

-- Pregunta 23
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS TRABAJADOR,
       E.SALARY AS SUELDO_TRABAJADOR,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE,
       M.SALARY AS SUELDO_JEFE
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
WHERE E.SALARY > M.SALARY;

-- Pregunta 24
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE,
       J.JOB_TITLE AS CARGO_JEFE
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
JOIN OEHR_JOBS J ON J.JOB_ID = M.JOB_ID
ORDER BY D.DEPARTMENT_ID;

-- Pregunta 25
SELECT E.EMPLOYEE_ID AS COD_TRABAJADOR,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS TRABAJADOR,
       J.JOB_TITLE AS CARGO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       L.CITY AS CIUDAD,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DEPARTAMENTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
ORDER BY D.DEPARTMENT_NAME, E.LAST_NAME;

-- Pregunta 26
SELECT E.EMPLOYEE_ID AS COD_TRABAJADOR,
       E.LAST_NAME AS APELLIDO,
       NVL(D.DEPARTMENT_NAME, 'SIN DEPARTAMENTO') AS DEPARTAMENTO,
       NVL(M.FIRST_NAME || ' ' || M.LAST_NAME, 'SIN JEFE') AS JEFE_DEPARTAMENTO
FROM OEHR_EMPLOYEES E
LEFT JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
LEFT JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID;

-- Pregunta 27
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS TRABAJADOR,
       D.DEPARTMENT_NAME AS DEPARTAMENTO_TRABAJADOR,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_ASOCIADO,
       DM.DEPARTMENT_NAME AS DEPARTAMENTO_JEFE
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
LEFT JOIN OEHR_DEPARTMENTS DM ON DM.DEPARTMENT_ID = M.DEPARTMENT_ID;

-- Pregunta 28
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, M.FIRST_NAME, M.LAST_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 3
   AND AVG(E.SALARY) > 5000;

-- Pregunta 29
SELECT E.EMPLOYEE_ID AS COD_TRABAJADOR,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS TRABAJADOR,
       E.SALARY AS SUELDO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DEPARTAMENTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
WHERE E.SALARY > (SELECT AVG(E2.SALARY)
                  FROM OEHR_EMPLOYEES E2
                  WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID);

-- Pregunta 30
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       MIN(E.SALARY) AS SUELDO_MINIMO,
       MAX(E.SALARY) AS SUELDO_MAXIMO,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = D.MANAGER_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, M.FIRST_NAME, M.LAST_NAME
HAVING COUNT(E.EMPLOYEE_ID) > 1
   AND AVG(E.SALARY) > (SELECT AVG(SALARY) FROM OEHR_EMPLOYEES);

-- Pregunta 31
SELECT JOB_ID AS CODIGO_OFICIO,
       AVG(MIN_SALARY) AS PROMEDIO_SUELDO_MINIMO
FROM OEHR_JOBS
GROUP BY JOB_ID
HAVING AVG(MIN_SALARY) > 3000;

-- Pregunta 32
SELECT SUBSTR(JOB_ID, 1, 2) AS AREA,
       ROUND(AVG(MIN_SALARY), 0) AS PROMEDIO_SUELDO_MINIMO
FROM OEHR_JOBS
GROUP BY SUBSTR(JOB_ID, 1, 2)
HAVING AVG(MIN_SALARY) > 4000;

-- Pregunta 33
SELECT JOB_ID AS CODIGO_OFICIO,
       AVG(MIN_SALARY) AS PROMEDIO_SUELDO_MINIMO
FROM OEHR_JOBS
GROUP BY JOB_ID
HAVING AVG(MIN_SALARY) BETWEEN 2500 AND 8000
ORDER BY AVG(MIN_SALARY) DESC;

-- Pregunta 34
SELECT SUBSTR(JOB_ID, 1, 2) AS AREA,
       COUNT(JOB_ID) AS CANTIDAD_OFICIOS,
       ROUND(AVG(MIN_SALARY), 0) AS PROMEDIO_SUELDO_MINIMO
FROM OEHR_JOBS
GROUP BY SUBSTR(JOB_ID, 1, 2)
HAVING COUNT(JOB_ID) >= 2
   AND AVG(MIN_SALARY) > 3000;

-- Pregunta 35
SELECT J.JOB_ID AS CODIGO_OFICIO,
       J.JOB_TITLE AS NOMBRE_OFICIO,
       J.MIN_SALARY AS MINIMO_CONFIGURADO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL
FROM OEHR_JOBS J
JOIN OEHR_EMPLOYEES E ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID, J.JOB_TITLE, J.MIN_SALARY
HAVING AVG(E.SALARY) > J.MIN_SALARY;

-- Pregunta 36
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(J.MIN_SALARY), 0) AS PROMEDIO_MINIMOS
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 2
   AND AVG(J.MIN_SALARY) > 4000;

-- Pregunta 37
SELECT SUBSTR(E.JOB_ID, 1, 2) AS AREA,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL,
       ROUND(AVG(J.MIN_SALARY), 0) AS PROMEDIO_MINIMOS
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
GROUP BY SUBSTR(E.JOB_ID, 1, 2)
HAVING COUNT(E.EMPLOYEE_ID) >= 3
   AND AVG(E.SALARY) > AVG(J.MIN_SALARY) * 1.5;

-- Pregunta 38
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       COUNT(DISTINCT E.JOB_ID) AS OFICIOS_DISTINTOS,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL,
       ROUND(AVG(J.MIN_SALARY), 0) AS PROMEDIO_MINIMOS
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(DISTINCT E.JOB_ID) >= 2
   AND AVG(E.SALARY) > AVG(J.MIN_SALARY);

-- Pregunta 39
SELECT J.JOB_ID AS CODIGO_OFICIO,
       J.JOB_TITLE AS NOMBRE_OFICIO,
       J.MIN_SALARY AS MINIMO_CONFIGURADO,
       J.MAX_SALARY AS MAXIMO_CONFIGURADO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES,
       ROUND(AVG(E.SALARY), 0) AS PROMEDIO_REAL
FROM OEHR_JOBS J
JOIN OEHR_EMPLOYEES E ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID, J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY
HAVING COUNT(E.EMPLOYEE_ID) > 1
   AND AVG(E.SALARY) > (SELECT AVG(SALARY) FROM OEHR_EMPLOYEES);

-- Pregunta 40
SELECT F.AREA,
       F.CANTIDAD_OFICIOS,
       F.PROMEDIO_MINIMOS,
       T.CANTIDAD_TRABAJADORES
FROM (SELECT SUBSTR(JOB_ID, 1, 2) AS AREA,
             COUNT(JOB_ID) AS CANTIDAD_OFICIOS,
             ROUND(AVG(MIN_SALARY), 0) AS PROMEDIO_MINIMOS
      FROM OEHR_JOBS
      GROUP BY SUBSTR(JOB_ID, 1, 2)
      HAVING AVG(MIN_SALARY) > (SELECT AVG(MIN_SALARY) FROM OEHR_JOBS)) F
JOIN (SELECT SUBSTR(JOB_ID, 1, 2) AS AREA,
             COUNT(EMPLOYEE_ID) AS CANTIDAD_TRABAJADORES
      FROM OEHR_EMPLOYEES
      GROUP BY SUBSTR(JOB_ID, 1, 2)
      HAVING COUNT(EMPLOYEE_ID) >= 2) T ON T.AREA = F.AREA;

-- Pregunta 41
SELECT EMPLOYEE_ID AS CODIGO,
       FIRST_NAME AS NOMBRE,
       LAST_NAME AS APELLIDO
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM OEHR_EMPLOYEES
                        WHERE UPPER(LAST_NAME) = 'WHALEN');

-- Pregunta 42
SELECT E.EMPLOYEE_ID AS COD_EMPLEADO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE_EMPLEADO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'));

-- Pregunta 43
SELECT E.EMPLOYEE_ID AS COD_EMPLEADO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE_EMPLEADO,
       E.SALARY AS SUELDO,
       J.JOB_TITLE AS CARGO
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'))
  AND E.SALARY > 7000
ORDER BY E.SALARY DESC;

-- Pregunta 44
SELECT E.EMPLOYEE_ID AS COD_EMPLEADO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE_EMPLEADO,
       J.JOB_TITLE AS CARGO,
       J.MIN_SALARY AS SUELDO_MINIMO_CARGO
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'));

-- Pregunta 45
SELECT E.EMPLOYEE_ID AS COD_EMPLEADO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE_EMPLEADO,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DIRECTO
FROM OEHR_EMPLOYEES E
LEFT JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = E.MANAGER_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'));

-- Pregunta 46
SELECT D.DEPARTMENT_ID AS COD_DEPARTAMENTO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_DEPARTMENTS D
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'))
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 2;

-- Pregunta 47
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       J.JOB_TITLE AS CARGO,
       L.CITY AS CIUDAD,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DIRECTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = E.MANAGER_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'));

-- Pregunta 48
SELECT D.DEPARTMENT_NAME AS DEPARTAMENTO,
       L.CITY AS CIUDAD,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       MIN(E.SALARY) AS SUELDO_MINIMO,
       MAX(E.SALARY) AS SUELDO_MAXIMO,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO
FROM OEHR_DEPARTMENTS D
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
JOIN OEHR_EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'))
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.CITY
HAVING AVG(E.SALARY) > 5000
   AND MAX(E.SALARY) - MIN(E.SALARY) <> 0;

-- Pregunta 49
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       E.SALARY AS SUELDO,
       ROUND((SELECT AVG(E2.SALARY)
              FROM OEHR_EMPLOYEES E2
              WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID), 0) AS PROMEDIO_DEPARTAMENTAL
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(LAST_NAME) IN ('WHALEN', 'KING'))
  AND E.SALARY > (SELECT AVG(E3.SALARY)
                  FROM OEHR_EMPLOYEES E3
                  WHERE E3.DEPARTMENT_ID = E.DEPARTMENT_ID);

-- Pregunta 50
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       L.CITY AS CIUDAD,
       C.COUNTRY_NAME AS PAIS,
       J.JOB_TITLE AS CARGO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
JOIN OEHR_COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE L.CITY IN (SELECT LR.CITY
                 FROM OEHR_EMPLOYEES ER
                 JOIN OEHR_DEPARTMENTS DR ON DR.DEPARTMENT_ID = ER.DEPARTMENT_ID
                 JOIN OEHR_LOCATIONS LR ON LR.LOCATION_ID = DR.LOCATION_ID
                 WHERE UPPER(ER.LAST_NAME) IN ('WHALEN', 'KING'));

-- Pregunta 51
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 1) || SUBSTR(E.LAST_NAME, 2, 1) ||
             E.JOB_ID || '@pruebasql.cl') AS CORREO_PROPUESTO,
       E.COMMISSION_PCT AS COMISION
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'NEENA'
                            AND UPPER(LAST_NAME) = 'KOCHHAR');

-- Pregunta 52
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 2) || SUBSTR(E.LAST_NAME, 1, 3)) AS USUARIO,
       E.COMMISSION_PCT AS COMISION
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL');

-- Pregunta 53
SELECT E.EMPLOYEE_ID AS CODIGO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS NOMBRE,
       E.SALARY AS SUELDO,
       E.COMMISSION_PCT AS COMISION
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL')
ORDER BY E.SALARY DESC;

-- Pregunta 54
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 1) || E.LAST_NAME || '@empresa.cl') AS CORREO,
       J.JOB_TITLE AS CARGO
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL');

-- Pregunta 55
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 1) || SUBSTR(E.LAST_NAME, -2) || '@rrhh.cl') AS CORREO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       L.CITY AS CIUDAD
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL');

-- Pregunta 56
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       TO_CHAR(E.COMMISSION_PCT * 100) || '%' AS PORCENTAJE_COMISION,
       E.SALARY * E.COMMISSION_PCT AS COMISION_MENSUAL
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL');

-- Pregunta 57
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 1) || SUBSTR(E.LAST_NAME, 1, 3) ||
             E.JOB_ID || '@sql.cl') AS CORREO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       J.JOB_TITLE AS CARGO,
       L.CITY AS CIUDAD,
       C.COUNTRY_NAME AS PAIS,
       M.FIRST_NAME || ' ' || M.LAST_NAME AS JEFE_DIRECTO
FROM OEHR_EMPLOYEES E
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
JOIN OEHR_COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN OEHR_EMPLOYEES M ON M.EMPLOYEE_ID = E.MANAGER_ID
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL');

-- Pregunta 58
SELECT E.JOB_ID AS CARGO,
       COUNT(E.EMPLOYEE_ID) AS CANTIDAD_EMPLEADOS,
       ROUND(AVG(E.SALARY), 0) AS SUELDO_PROMEDIO,
       ROUND(AVG(E.COMMISSION_PCT), 2) AS COMISION_PROMEDIO
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL')
GROUP BY E.JOB_ID
HAVING COUNT(E.EMPLOYEE_ID) >= 2
   AND AVG(E.SALARY) NOT BETWEEN 5000 AND 10000;

-- Pregunta 59
SELECT E.EMPLOYEE_ID AS CODIGO,
       E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       E.JOB_ID AS CARGO,
       E.SALARY AS SUELDO,
       E.COMMISSION_PCT AS COMISION
FROM OEHR_EMPLOYEES E
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM OEHR_EMPLOYEES
                          WHERE UPPER(FIRST_NAME) = 'JOHN'
                            AND UPPER(LAST_NAME) = 'RUSSELL')
  AND E.SALARY > (SELECT AVG(E2.SALARY)
                  FROM OEHR_EMPLOYEES E2
                  WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
                    AND E2.JOB_ID = E.JOB_ID
                    AND E2.COMMISSION_PCT IS NOT NULL);

-- Pregunta 60
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLEADO,
       LOWER(SUBSTR(E.FIRST_NAME, 1, 1) || SUBSTR(E.LAST_NAME, 2, 2) ||
             E.JOB_ID || '@desafio.cl') AS CORREO_PROPUESTO,
       J.JOB_TITLE AS CARGO,
       D.DEPARTMENT_NAME AS DEPARTAMENTO,
       L.CITY AS CIUDAD,
       E.SALARY AS SUELDO,
       E.COMMISSION_PCT AS COMISION
FROM OEHR_EMPLOYEES E
JOIN OEHR_JOBS J ON J.JOB_ID = E.JOB_ID
JOIN OEHR_DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN OEHR_LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
WHERE E.COMMISSION_PCT IS NOT NULL
  AND E.SALARY NOT BETWEEN 5000 AND 10000
  AND L.CITY IN (SELECT LR.CITY
                 FROM OEHR_EMPLOYEES NK
                 JOIN OEHR_DEPARTMENTS DR ON DR.DEPARTMENT_ID = NK.DEPARTMENT_ID
                 JOIN OEHR_LOCATIONS LR ON LR.LOCATION_ID = DR.LOCATION_ID
                 WHERE UPPER(NK.FIRST_NAME) = 'JOHN'
                   AND UPPER(NK.LAST_NAME) = 'RUSSELL');
