
-- =============================================================
-- U2_C4 — SOLUCIÓN INTEGRAL (GIGH_*), alineada a U2_C1 / U2_C1-2
-- Prácticas: %TYPE, secuencias + triggers + PA (sin PK en parámetros)
-- =============================================================

-- -------------------------------------------------------------
-- Limpieza idempotente
-- -------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GIGH_DETALLE_NOTAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GIGH_USUARIO CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GIGH_DETALLE_NOTAS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2289,-02289) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GIGH_USUARIO';       EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2289,-02289) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE GIGH_CARGA_USUARIOS';   EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
-- -------------------------------------------------------------
-- 1) TABLA GIGH_DETALLE_NOTAS + PK + secuencia + triggers
-- -------------------------------------------------------------
CREATE TABLE GIGH_DETALLE_NOTAS(
  NRO_DETALLE NUMBER CONSTRAINT PK_GIGH_DETALLE_NOTAS PRIMARY KEY,
  NOTA1       NUMBER,
  NOTA2       NUMBER,
  NOTA3       NUMBER,
  PROMEDIO    NUMBER
);

CREATE SEQUENCE SEQ_GIGH_DETALLE_NOTAS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_GIGH_DETALLE_NOTAS_PK
BEFORE INSERT ON GIGH_DETALLE_NOTAS
FOR EACH ROW
WHEN (NEW.NRO_DETALLE IS NULL)
BEGIN
  :NEW.NRO_DETALLE := SEQ_GIGH_DETALLE_NOTAS.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_GIGH_PROMEDIO_AUTO
BEFORE INSERT OR UPDATE OF NOTA1, NOTA2, NOTA3 ON GIGH_DETALLE_NOTAS
FOR EACH ROW
BEGIN
  :NEW.PROMEDIO := ROUND((NVL(:NEW.NOTA1,0)+NVL(:NEW.NOTA2,0)+NVL(:NEW.NOTA3,0))/3,1);
END;
/
-- Pruebas rápidas
INSERT INTO GIGH_DETALLE_NOTAS (NRO_DETALLE, NOTA1, NOTA2, NOTA3, PROMEDIO) VALUES (1,5,6,3,2.5);
INSERT INTO GIGH_DETALLE_NOTAS (NRO_DETALLE, NOTA1, NOTA2, NOTA3) VALUES (NULL,4,5,6);

-- -------------------------------------------------------------
-- 2) TABLA GIGH_USUARIO (estructura según U2_C1) + correo único
-- -------------------------------------------------------------
CREATE TABLE GIGH_USUARIO(
  COD_USUARIO        NUMBER CONSTRAINT PK_GIGH_USUARIO PRIMARY KEY,
  NOMBRE_USUARIO     VARCHAR2(25),
  APELLIDO1_USUARIO  VARCHAR2(25),
  APELLIDO2_USUARIO  VARCHAR2(25),
  CORREO             VARCHAR2(200) NOT NULL
);

ALTER TABLE GIGH_USUARIO ADD CONSTRAINT UQ_GIGH_USUARIO_CORREO UNIQUE (CORREO);

CREATE SEQUENCE SEQ_GIGH_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_GIGH_USUARIO_PK
BEFORE INSERT ON GIGH_USUARIO
FOR EACH ROW
WHEN (NEW.COD_USUARIO IS NULL)
BEGIN
  :NEW.COD_USUARIO := SEQ_GIGH_USUARIO.NEXTVAL;
END;
/
-- Mayúsculas en campos de texto (coincide con práctica pedida en U2_C4)
CREATE OR REPLACE TRIGGER TRG_GIGH_USUARIO_UPPER
BEFORE INSERT OR UPDATE ON GIGH_USUARIO
FOR EACH ROW
BEGIN
  :NEW.NOMBRE_USUARIO    := UPPER(NVL(:NEW.NOMBRE_USUARIO,   ''));
  :NEW.APELLIDO1_USUARIO := UPPER(NVL(:NEW.APELLIDO1_USUARIO,''));
  :NEW.APELLIDO2_USUARIO := UPPER(NVL(:NEW.APELLIDO2_USUARIO,''));
  :NEW.CORREO            := UPPER(NVL(:NEW.CORREO,           ''));
END;
/
-- -------------------------------------------------------------
-- 3) PA sin PK en parámetros, usando %TYPE y correo único
--    Formato base: AAAA.APELLIDO2@TESTSQL.CL (AAAA = 4 primeras de APELLIDO1)
--    Si existe, agrega sufijo 1,2,3... antes de la @
-- -------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GIGH_CARGA_USUARIOS(
  NOMBRE_USUARIO_P     IN GIGH_USUARIO.NOMBRE_USUARIO%TYPE,
  APELLIDO1_USUARIO_P  IN GIGH_USUARIO.APELLIDO1_USUARIO%TYPE,
  APELLIDO2_USUARIO_P  IN GIGH_USUARIO.APELLIDO2_USUARIO%TYPE
) AS
  v_nom   GIGH_USUARIO.NOMBRE_USUARIO%TYPE    := TRIM(NOMBRE_USUARIO_P);
  v_ap1   GIGH_USUARIO.APELLIDO1_USUARIO%TYPE := TRIM(APELLIDO1_USUARIO_P);
  v_ap2   GIGH_USUARIO.APELLIDO2_USUARIO%TYPE := TRIM(APELLIDO2_USUARIO_P);
  v_base  VARCHAR2(200);
  v_mail  VARCHAR2(200);
  v_idx   NUMBER := 0;
  v_cnt   NUMBER;
BEGIN
  v_base := SUBSTR(UPPER(v_ap1),1,4) || '.' || UPPER(v_ap2) || '@TESTSQL.CL';
  v_mail := v_base;

  LOOP
    SELECT COUNT(*) INTO v_cnt FROM GIGH_USUARIO WHERE CORREO = v_mail;
    EXIT WHEN v_cnt = 0;
    v_idx  := v_idx + 1;
    v_mail := REGEXP_REPLACE(v_base, '(@TESTSQL\.CL)$', TO_CHAR(v_idx) || '\1');
  END LOOP;

  INSERT INTO GIGH_USUARIO (NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, CORREO)
  VALUES (v_nom, v_ap1, v_ap2, v_mail);
END;
/
-- -------------------------------------------------------------
-- 4) BLOQUE DE PRUEBAS (igual al enunciado)
-- -------------------------------------------------------------
BEGIN
  GIGH_CARGA_USUARIOS('Carlos','Castro','Bustamante');
  GIGH_CARGA_USUARIOS('Carlos','Castro','Bustamante');
  GIGH_CARGA_USUARIOS('Felipe','Oyarzun','Santelices');
  GIGH_CARGA_USUARIOS('Macarena','Urbina','Figueroa');
  GIGH_CARGA_USUARIOS('Carmen','Bustos','Bustamante');
END;
/
PROMPT === VERIFICACIÓN: DETALLE_NOTAS ===
SELECT * FROM GIGH_DETALLE_NOTAS ORDER BY NRO_DETALLE;

PROMPT === VERIFICACIÓN: USUARIO (correo único y mayúsculas) ===
SELECT COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, CORREO
FROM GIGH_USUARIO ORDER BY COD_USUARIO;
