create or replace TRIGGER TRG_GIGH_USUARIO_PK
BEFORE INSERT
ON GIGH_USUARIO
FOR EACH ROW
DECLARE 
    TEMP NUMBER;
BEGIN
	SELECT MAX(COD_USUARIO)+1 INTO TEMP
	FROM GIGH_USUARIO;
	IF TEMP IS NULL THEN
		TEMP := 1;
	END IF;
    :NEW.COD_USUARIO := TEMP;
END;
/



-- CREAR UNA TABLA DE NOMBRE DETALLE_NOTAS, CON SUS PREFIJOS 
-- CORRESPONDIENTES, Y LOS SIGUIENTES CAMPOS: NRO_DETALLE, NOTA1, 
-- NOTA2, NOTA3, PROMEDIO, CON TODOS SUS CAMPOS DE TIPO NUMBER
-- Y RESTRICCIÓN PRIMARIA EN EL NRO_DETALLE.

CREATE TABLE GIGH_DETALLE_NOTAS(
	NRO_DETALLE NUMBER,
	NOTA1 NUMBER,
	NOTA2 NUMBER,
	NOTA3 NUMBER,
	PROMEDIO NUMBER,
	CONSTRAINT PK_GIGH_DETALLE_NOTAS PRIMARY KEY(NRO_DETALLE)
);


-- REALIZAR UN INSERT A ESTA TABLA

INSERT INTO GIGH_DETALLE_NOTAS(NRO_DETALLE,NOTA1,NOTA2,NOTA3,PROMEDIO)
	VALUES(1,5,6,3,2.5);


-- CREAR UN TRIGGER QUE CALCULE EL PROMEDIO AUTOMÁTICAMENTE AL 
-- INSERTAR (Y ACTUALIZAR) LOS VALORES DE LAS NOTAS.

CREATE OR REPLACE TRIGGER TRG_GIGH_PROMEDIO_AUTO
BEFORE INSERT OR UPDATE OF NOTA1, NOTA2, NOTA3 ON GIGH_DETALLE_NOTAS
FOR EACH ROW
BEGIN
	:NEW.PROMEDIO := ROUND((NVL(:NEW.NOTA1,0)+NVL(:NEW.NOTA2,0)+NVL(:NEW.NOTA3,0))/3,1);
END;
/

-- INSERT DE PRUEBA SIN PROMEDIO

INSERT INTO GIGH_DETALLE_NOTAS(NRO_DETALLE,NOTA1,NOTA2,NOTA3)
	VALUES(2,4,5,6);


-- TAREA 1
-- SE SOLICITA QUE GENERE UN TRIGGER QUE SE ENCARGUE DE OTORGAR LA CLAVE 
-- PRIMARIA PARA LA TABLA DETALLE DE NOTAS Y OTRO PARA LA TABLA USUARIO
-- TRABAJADA EN CLASES ANTERIORES.
-- COMO TAMBIÉN GENERAR OTRO TRIGGER QUE SE ENCARGUE DE TRABAJAR LOS 
-- CAMPOS DE TIPO TEXTO EVALUÁNDOLOS EN MAYÚSCULA PARA LA TABLA USUARIO.


-- SECUENCIAS
CREATE SEQUENCE SEQ_GIGH_DETALLE_NOTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GIGH_USUARIO START WITH 1 INCREMENT BY 1;



-- TABLA USUARIO (EN SINGULAR, COMO EN U2_C1)

CREATE TABLE GIGH_USUARIO(
	COD_USUARIO NUMBER,
	NOMBRE_USUARIO VARCHAR2(25),
	APELLIDO1_USUARIO VARCHAR2(25),
	APELLIDO2_USUARIO VARCHAR2(25),
	EMAIL VARCHAR2(200) NOT NULL,
	CONSTRAINT PK_GIGH_USUARIO PRIMARY KEY(COD_USUARIO)
);

-- UNICIDAD EN EMAIL
ALTER TABLE GIGH_USUARIO ADD CONSTRAINT UQ_GIGH_USUARIO_EMAIL UNIQUE(EMAIL);


-- TRIGGER PK USUARIO (CUANDO COD_USUARIO VIENE NULL)
CREATE OR REPLACE TRIGGER TRG_GIGH_USUARIO_PK
BEFORE INSERT ON GIGH_USUARIO
FOR EACH ROW
WHEN (NEW.COD_USUARIO IS NULL)
BEGIN
	:NEW.COD_USUARIO := SEQ_GIGH_USUARIO.NEXTVAL;
END;


-- TRIGGER MAYÚSCULAS CAMPOS TEXTO (USUARIO)
CREATE OR REPLACE TRIGGER TRG_GIGH_USUARIO_UPPER
BEFORE INSERT OR UPDATE ON GIGH_USUARIO
FOR EACH ROW
BEGIN
	:NEW.NOMBRE_USUARIO := UPPER(NVL(:NEW.NOMBRE_USUARIO,''));
	:NEW.APELLIDO1_USUARIO := UPPER(NVL(:NEW.APELLIDO1_USUARIO,''));
	:NEW.APELLIDO2_USUARIO := UPPER(NVL(:NEW.APELLIDO2_USUARIO,''));
	:NEW.EMAIL := UPPER(NVL(:NEW.EMAIL,''));
END;



-- LUEGO DE RESOLVER LA TAREA 1
-- SE PIDE TRABAJAR EN ACTUALIZAR EL PROCEDIMIENTO ALMACENADO DE 
-- CARGA DE USUARIOS (PARA LA TABLA USUARIO) Y QUITAR LA CLAVE PRIMARIA DEL
-- PROCEDIMIENTO COMO TAL Y DE SU INSERT ASOCIADO, PARA LUEGO REALIZAR
-- LAS PRUEBAS CORRESPONDIENTES.


-- PROCEDIMIENTO ALMACENADO (SIN PK EN PARÁMETROS)
CREATE OR REPLACE PROCEDURE GIGH_CARGA_USUARIOS(
	NOMBRE_USUARIO_P IN GIGH_USUARIO.NOMBRE_USUARIO%TYPE,
	APELLIDO1_USUARIO_P IN GIGH_USUARIO.APELLIDO1_USUARIO%TYPE,
	APELLIDO2_USUARIO_P IN GIGH_USUARIO.APELLIDO2_USUARIO%TYPE
)
IS

BEGIN
	LOCK TABLE GIGH_USUARIO IN ROW EXCLUSIVE MODE;


	INSERT INTO GIGH_USUARIO(NOMBRE_USUARIO,APELLIDO1_USUARIO,APELLIDO2_USUARIO,EMAIL)
		VALUES(
			NOMBRE_USUARIO_P,
			APELLIDO1_USUARIO_P,
			APELLIDO2_USUARIO_P,
			VERIFICAR_EMAIL(NOMBRE_USUARIO_P,APELLIDO1_USUARIO_P,APELLIDO2_USUARIO_P)
		);

	COMMIT;
	EXCEPTION
		WHEN PROGRAM_ERROR THEN
			RAISE_APPLICATION_ERROR(-6501,'ERROR INTERNO DEL PROGRAMA.');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'ERROR INESPERADO.');
		ROLLBACK;
END;




CREATE OR REPLACE FUNCTION VERIFICAR_EMAIL(
	NOMBRE_USUARIO_F IN GIGH_USUARIO.NOMBRE_USUARIO%TYPE,
	APELLIDO1_USUARIO_F IN GIGH_USUARIO.APELLIDO1_USUARIO%TYPE,
	APELLIDO2_USUARIO_F IN GIGH_USUARIO.APELLIDO2_USUARIO%TYPE
)	
	RETURN VARCHAR2
IS	
	V_EMAIL_BASE            VARCHAR2(50);   -- AAAA.APELLIDO2@TESTSQL.CL
	V_EXISTENCIAS_EMAIL      NUMBER;
BEGIN
	-- FORMATO: AAAA.APELLIDO2@TESTSQL.CL (AAAA = 4 PRIMERAS DE APELLIDO1)
	V_EMAIL_BASE     :=  SUBSTR(UPPER(NOMBRE_USUARIO_F),1,2)  || SUBSTR(UPPER(APELLIDO1_USUARIO_F),3,2) || '.' || UPPER(APELLIDO2_USUARIO_F);


	-- SI YA EXISTE, AGREGAR SUFIJOS 1,2,3... ANTES DE LA @
	
	SELECT COUNT(*) INTO V_EXISTENCIAS_EMAIL FROM GIGH_USUARIO WHERE EMAIL LIKE V_EMAIL_BASE || '%';
	IF V_EXISTENCIAS_EMAIL > 0 THEN
		V_EMAIL_BASE:=  V_EMAIL_BASE || TO_CHAR(V_EXISTENCIAS_EMAIL);
	END IF;

	V_EMAIL_BASE:=  V_EMAIL_BASE || '@TESTSQL.CL';

	RETURN V_EMAIL_BASE;
END;





-- EMAIL SEGÚN LO YA INDICADO POR REQUERIMIENTOS ANTERIORES: 
-- CAST.BUSTAMANTE@TESTSQL.CL Y PARA EL SEGUNDO: CAST.BUSTAMANTE1@TESTSQL.CL
-- EN CASO DE EXISTIR UN 3RO CAST.BUSTAMANTE2@TESTSQL.CL Y ASÍ SUCESIVAMENTE
-- UTILIZANDO UNA SECUENCIA PARA ESTO O UNA CONSULTA, MANEJANDO LAS RESTRICCIONES 
-- INDICADAS POR EL EJEMPLO. 


BEGIN
	GIGH_CARGA_USUARIOS('CARLOS','CASTRO','BUSTAMANTE');
	GIGH_CARGA_USUARIOS('FELIPE','OYARZUN','SANTELICES');
	GIGH_CARGA_USUARIOS('MACARENA','URBINA','FIGUEROA');
	GIGH_CARGA_USUARIOS('CARLOS','CASTRO','BUSTAMANTE');
	GIGH_CARGA_USUARIOS('CARMEN','BUSTOS','BUSTAMANTE');	
END;


-- VERIFICACIÓN


SELECT * FROM GIGH_DETALLE_NOTAS;
SELECT COD_USUARIO,NOMBRE_USUARIO,APELLIDO1_USUARIO,APELLIDO2_USUARIO,EMAIL FROM GIGH_USUARIO;