-- PARA ACCEDER AL TIPO DE DATO DE UN CAMPO DE UNA TABLA, SE TRABAJA CON LA
-- SIGUIENTE INSTRUCCIÓN: NOMBRE_TABLA.NOMBRE_CAMPO%TYPE

-- SE SOLICITA UN PROCEDIMIENTO ALMACENADO QUE SE ENCARGUE DE INGRESAR DATOS A LA
-- TABLA USUARIO, DE NOMBRE CARGA_USUARIOS, QUE INCLUYA CONTROL DE CONCURRENCIA

CREATE OR REPLACE PROCEDURE GIGH_CARGA_USUARIOS(
	COD_USUARIO_P NUMBER,
	NOMBRE_USUARIO_P VARCHAR2,
	APELLIDO1_USUARIO_P VARCHAR2,
	APELLIDO2_USUARIO_P VARCHAR2
)
IS
BEGIN
	-- LOCK TABLE NOMBRE_TABLA IN MODO_BLOQUEO MODE; -- CONTROL DE CONCURRENCIA
	LOCK TABLE GIGH_USUARIO IN ROW EXCLUSIVE MODE;
	INSERT INTO GIGH_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
	VALUES(COD_USUARIO_P, NOMBRE_USUARIO_P,APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);
END;


-- EJECUCIÓN DEL PA


BEGIN
	DELETE FROM GIGH_USUARIO;
	GIGH_CARGA_USUARIOS(1,'CARLOS','CASTRO','BUSTAMANTE');
	GIGH_CARGA_USUARIOS(2,'JUAN','SOLER','GARCIA');
	GIGH_CARGA_USUARIOS(3,'MACARENA', 'URBINA', 'FIGUEROA');
	GIGH_CARGA_USUARIOS(4,'JOSE', 'REYES', 'CASTRO');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM GIGH_USUARIO;


------------------TAREA EN CLASE -------------------------------------------------
-- MODIFICAR EL PROCEDIMIENTO ALMACENADO ANTERIOR, E INCLUIR CONTROL DE TRANSACCIONES

CREATE OR REPLACE PROCEDURE GIGH_CARGA_USUARIOS(
	COD_USUARIO_P NUMBER,
	NOMBRE_USUARIO_P VARCHAR2,
	APELLIDO1_USUARIO_P VARCHAR2,
	APELLIDO2_USUARIO_P VARCHAR2
)
IS
BEGIN
	LOCK TABLE GIGH_USUARIO IN ROW EXCLUSIVE MODE;

	INSERT INTO GIGH_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
	VALUES(COD_USUARIO_P, NOMBRE_USUARIO_P,APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);

	COMMIT;
	EXCEPTION
		WHEN PROGRAM_ERROR THEN
			RAISE_APPLICATION_ERROR(-6501,'ERROR DE PROGRAMA Y/O ASIGNACION DE VARIABLES');
		WHEN STORAGE_ERROR THEN
			RAISE_APPLICATION_ERROR(-6500,'SE ACABO LA MEMORIA, O ESTA ES CORRUPTA');
		WHEN ROWTYPE_MISMATCH THEN
			RAISE_APPLICATION_ERROR(-6504,'ERROR DE ASIGNACION DE VARIABLES');
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20010,'OCURRIO UN ERROR');
		ROLLBACK;
END;



-- EJECUCIÓN DEL PA
BEGIN
	DELETE FROM GIGH_USUARIO;
	GIGH_CARGA_USUARIOS(1,'CARLOS','CASTRO','BUSTAMANTE');
	GIGH_CARGA_USUARIOS(2,'JUAN','SOLER','GARCIA');
	GIGH_CARGA_USUARIOS(3,'MACARENA', 'URBINA', 'FIGUEROA');
	GIGH_CARGA_USUARIOS(4,'JOSE', 'REYES', 'CASTRO');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM GIGH_USUARIO;


----------------------------------------------------------------------------------
----------------------------TAREA-------------------------------------------------

-- CÓMO PODRÍA GENERAR UN PROCEDIMIENTO INTEGRAL, QUE SE ENCARGUE DE REALIZAR
-- LAS 3 OPERACIONES DE LOS REQUERIMIENTOS ANTERIORES EN UN SOLO PROCEDIMIENTO ALMACENADO,
-- ESTE DEBE INCLUIR CONTROL DE CONCURRENCIA, COMO TAMBIÉN CONTROL DE TRANSACCIONES
-- Y MANEJO DE EXCEPCIONES, DE NOMBRE IUD_USUARIOS, CON SU PREFIJO CORRESPONDIENTE.

CREATE OR REPLACE PROCEDURE GIGH_IUD_USUARIO(
    OPERACION_P VARCHAR2,
    COD_USUARIO_P NUMBER,
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2
)
IS
BEGIN
    LOCK TABLE GIGH_USUARIO IN ROW EXCLUSIVE MODE;

    IF UPPER(OPERACION_P) = 'I' THEN

        INSERT INTO GIGH_USUARIO(
            COD_USUARIO,
            NOMBRE_USUARIO,
            APELLIDO1_USUARIO,
            APELLIDO2_USUARIO
        )
        VALUES(
            COD_USUARIO_P,
            NOMBRE_USUARIO_P,
            APELLIDO1_USUARIO_P,
            APELLIDO2_USUARIO_P
        );

    ELSIF UPPER(OPERACION_P) = 'U' THEN
        UPDATE GIGH_USUARIO
        SET NOMBRE_USUARIO = NOMBRE_USUARIO_P,
            APELLIDO1_USUARIO = APELLIDO1_USUARIO_P,
            APELLIDO2_USUARIO = APELLIDO2_USUARIO_P
        WHERE COD_USUARIO = COD_USUARIO_P;

    ELSIF UPPER(OPERACION_P) = 'D' THEN
        DELETE FROM GIGH_USUARIO
        WHERE COD_USUARIO = COD_USUARIO_P;

    ELSE
        RAISE_APPLICATION_ERROR(-20001,'OPERACION INVALIDA. UTILICE I, U O D');
    END IF;

    COMMIT;
    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20002,'ERROR DE PROGRAMA Y/O ASIGNACION DE VARIABLES');
        WHEN STORAGE_ERROR THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20003,'SE ACABO LA MEMORIA, O ESTA ES CORRUPTA');
        WHEN ROWTYPE_MISMATCH THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20004,'ERROR DE ASIGNACION DE VARIABLES');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20010,'OCURRIO UN ERROR');

END GIGH_IUD_USUARIO;
/

-------------------------------------------------------------------------
-------------------------------------------------------------------------
-------------------------------------------------------------------------




-- EJECUCIÓN DEL PA PARA INSERTAR
BEGIN
	DELETE FROM GIGH_USUARIO;
	GIGH_IUD_USUARIO('i',1,'CARLOS','CASTRO','BUSTAMANTE');
	GIGH_IUD_USUARIO('i',2,'JUAN','SOLER','GARCIA');
	GIGH_IUD_USUARIO('I',3,'MACARENA', 'URBINA', 'FIGUEROA');
	GIGH_IUD_USUARIO('I',4,'JOSE', 'REYES', 'CASTRO');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM GIGH_USUARIO;

-- QUISIERA ACTUALIZAR LOS DATOS JUAN SOLER, YA QUE HAY UN ERROR EN SU APELLIDO2,
-- EL CUAL DEBE SER SEPÚLVEDA.

-- EJECUCIÓN DEL PA PARA ACTUALIZAR
BEGIN
	GIGH_IUD_USUARIO('U',2,'JUAN','SOLER','SEPÚLVEDA');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM GIGH_USUARIO;


-- QUISIERA BORRAR LOS DATOS JUAN SOLER, YA QUE DESDE AHORA NO EXISTE
-- EN LA BASE DE DATOS

-- EJECUCIÓN DEL PA PARA BORRAR

BEGIN
	GIGH_IUD_USUARIO('d',2);
END;
-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM GIGH_USUARIO;
