CREATE OR REPLACE PORCEDURE CACB_MODIFICA_USUARIOS(
    NOMRBE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_2 VARCHAR2,
    COD_USUARIO_P NUMBER
)
IS 
BEGIN
    UPDATE CACB_USUARIO SET
        NOMBRE_USUARIO = NOMBRE_USUARIO_P,
        APELLIDO_USUARIO = APELLIDO