
  CREATE TABLE "OEHR_EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(6,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 207 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(25) CONSTRAINT "OEHR_EMP_LAST_NAME_NN" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(25) CONSTRAINT "OEHR_EMP_EMAIL_NN" NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20), 
	"HIRE_DATE" DATE CONSTRAINT "OEHR_EMP_HIRE_DATE_NN" NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) CONSTRAINT "OEHR_EMP_JOB_NN" NOT NULL ENABLE, 
	"SALARY" NUMBER(8,2), 
	"COMMISSION_PCT" NUMBER(2,2), 
	"MANAGER_ID" NUMBER(6,0), 
	"DEPARTMENT_ID" NUMBER(4,0), 
	 CONSTRAINT "OEHR_EMP_SALARY_MIN" CHECK (salary > 0) ENABLE, 
	 CONSTRAINT "OEHR_EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OEHR_EMP_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "OEHR_EMPLOYEES" ADD CONSTRAINT "OEHR_EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "OEHR_DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
  ALTER TABLE "OEHR_EMPLOYEES" ADD CONSTRAINT "OEHR_EMP_JOB_FK" FOREIGN KEY ("JOB_ID")
	  REFERENCES "OEHR_JOBS" ("JOB_ID") ENABLE;
  ALTER TABLE "OEHR_EMPLOYEES" ADD CONSTRAINT "OEHR_EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "OEHR_EMPLOYEES" ("EMPLOYEE_ID") ENABLE;

  CREATE INDEX "OEHR_EMP_DEPARTMENT_IX" ON "OEHR_EMPLOYEES" ("DEPARTMENT_ID") 
  ;

  CREATE INDEX "OEHR_EMP_JOB_IX" ON "OEHR_EMPLOYEES" ("JOB_ID") 
  ;

  CREATE INDEX "OEHR_EMP_MANAGER_IX" ON "OEHR_EMPLOYEES" ("MANAGER_ID") 
  ;

  CREATE INDEX "OEHR_EMP_NAME_IX" ON "OEHR_EMPLOYEES" ("LAST_NAME", "FIRST_NAME") 
  ;

   COMMENT ON COLUMN "OEHR_EMPLOYEES"."EMPLOYEE_ID" IS 'Primary key of oehr_employees table.';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."FIRST_NAME" IS 'First name of the employee. A not null column.';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."LAST_NAME" IS 'Last name of the employee. A not null column.';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."EMAIL" IS 'Email id of the employee';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."PHONE_NUMBER" IS 'Phone number of the employee includes country code and area code';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."HIRE_DATE" IS 'Date when the employee started on this job. A not null column.';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."JOB_ID" IS 'Current job of the employee foreign key to job_id column of the oehr_jobs table. A not null column.';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."SALARY" IS 'Monthly salary of the employee. Must be greater than zero (enforced by constraint oehr_emp_salary_min)';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."COMMISSION_PCT" IS 'Commission percentage of the employee Only employees in sales department elgible for commission percentage';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."MANAGER_ID" IS 'Manager id of the employee has same domain as manager_id in 
oehr_departments table. Foreign key to employee_id column of oehr_employees table.
(useful for reflexive joins and CONNECT BY query)';
   COMMENT ON COLUMN "OEHR_EMPLOYEES"."DEPARTMENT_ID" IS 'Department id where employee works foreign key to department_id column of the oehr_departments table';
   COMMENT ON TABLE "OEHR_EMPLOYEES"  IS 'oehr_employees table. Contains 107 rows. References with oehr_departments, 
oehr_jobs, oehr_job_history tables. Contains a self reference.';

  CREATE OR REPLACE EDITIONABLE TRIGGER "OEHR_UPDATE_JOB_HISTORY" 
  after update of job_id, department_id on oehr_employees
  for each row
declare
  l_sdate date;
begin
  if (:old.job_id != :new.job_id 
  or :old.department_id != :new.department_id) then
    for c1 in (select max(end_date) prev_start_date 
               from oehr_job_history
               where employee_id = :old.employee_id
              ) loop
      l_sdate := c1.prev_start_date+((24/60)/60);
    end loop;
   oehr_add_job_history(  :old.employee_id
                         , nvl(l_sdate,:old.hire_date)
                         , sysdate
                         , :old.job_id
                         , :old.department_id);
  end if;
end;
/
ALTER TRIGGER "OEHR_UPDATE_JOB_HISTORY" ENABLE;