
  CREATE TABLE "OEHR_INVENTORIES" 
   (	"PRODUCT_ID" NUMBER(6,0), 
	"WAREHOUSE_ID" NUMBER(3,0) CONSTRAINT "OEHR_INVENTORY_WAREHOUSE_ID_NN" NOT NULL ENABLE, 
	"QUANTITY_ON_HAND" NUMBER(8,0) CONSTRAINT "OEHR_INVENTORY_QOH_NN" NOT NULL ENABLE, 
	 CONSTRAINT "OEHR_INVENTORY_PK" PRIMARY KEY ("PRODUCT_ID", "WAREHOUSE_ID") DISABLE
   ) ;

  ALTER TABLE "OEHR_INVENTORIES" ADD CONSTRAINT "OEHR_INVENTORIES_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "OEHR_PRODUCT_INFORMATION" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "OEHR_INVENTORIES" ADD CONSTRAINT "OEHR_INVENTORIES_WAREHOUSES_FK" FOREIGN KEY ("WAREHOUSE_ID")
	  REFERENCES "OEHR_WAREHOUSES" ("WAREHOUSE_ID") ENABLE;

  CREATE INDEX "OEHR_INVENTORY_IX" ON "OEHR_INVENTORIES" ("WAREHOUSE_ID", "PRODUCT_ID") 
  ;

  CREATE INDEX "OEHR_INV_PRODUCT_IX" ON "OEHR_INVENTORIES" ("PRODUCT_ID") 
  ;

   COMMENT ON COLUMN "OEHR_INVENTORIES"."PRODUCT_ID" IS 'Part of concatenated primary key, references oehr_product_information.product_id.';
   COMMENT ON COLUMN "OEHR_INVENTORIES"."WAREHOUSE_ID" IS 'Part of concatenated primary key, references oehr_warehouses.warehouse_id.';
   COMMENT ON TABLE "OEHR_INVENTORIES"  IS 'Tracks availability of products by product_it and warehouse_id.';