-- =============================================================================
-- PRACTICA DE REFUERZO U2 - SOLUCIONES CAPITULO 1
-- SECCIÓN 1 — MODELO RELACIONAL Y ORDEN DE OBJETOS
-- =============================================================================
-- Habilidad central: modelo físico, restricciones, dependencias y limpieza idempotente.
-- Soluciones de referencia. Se aceptan alternativas equivalentes.
-- =============================================================================

-- PREGUNTA 1 - AFIANZAMIENTO
-- 
-- Escriba los CREATE TABLE de GIGH_CLIENTE y GIGH_PRODUCTOS con sus columnas, tipos, claves primarias y restricciones de obligatoriedad.
-- SOLUCION:
CREATE TABLE GIGH_CLIENTE(COD_CLIENTE NUMBER CONSTRAINT PK_GIGH_CLIENTE PRIMARY KEY,NOMBRE_CLIENTE VARCHAR2(50) NOT NULL,APELLIDO1_CLIENTE VARCHAR2(50) NOT NULL,APELLIDO2_CLIENTE VARCHAR2(50),EMAIL_CLIENTE VARCHAR2(100) NOT NULL CONSTRAINT UQ_GIGH_CLIENTE_EMAIL UNIQUE);
CREATE TABLE GIGH_PRODUCTOS(COD_PRODUCTO NUMBER CONSTRAINT PK_GIGH_PRODUCTOS PRIMARY KEY,NOMBRE_PRODUCTO VARCHAR2(50) NOT NULL,PRECIO_COMPRA NUMBER(12,2) NOT NULL,PRECIO_VENTA NUMBER(12,2) NOT NULL,CANTIDAD NUMBER DEFAULT 0,STOCK NUMBER DEFAULT 0);



-- PREGUNTA 2 - AFIANZAMIENTO
-- 
-- Complete las tablas GIGH_VENTA, GIGH_DETALLE_VENTA y GIGH_LOG_VENTAS. Incluya la clave primaria compuesta del detalle.
-- SOLUCION:
CREATE TABLE GIGH_VENTA(COD_VENTA NUMBER CONSTRAINT PK_GIGH_VENTA PRIMARY KEY,FECHA_VENTA DATE DEFAULT SYSDATE,TOTAL_VENTA NUMBER(12,2),COD_CLIENTE NUMBER NOT NULL CONSTRAINT FK_GIGH_VENTA_CLIENTE REFERENCES GIGH_CLIENTE);
CREATE TABLE GIGH_DETALLE_VENTA(COD_VENTA NUMBER,COD_PRODUCTO NUMBER,CANTIDAD NUMBER,VALOR_TOTAL NUMBER(12,2),CONSTRAINT PK_GIGH_DETALLE PRIMARY KEY(COD_VENTA,COD_PRODUCTO));
CREATE TABLE GIGH_LOG_VENTAS(COD_LOG NUMBER CONSTRAINT PK_GIGH_LOG PRIMARY KEY,INSTRUCCION VARCHAR2(50),DETALLE VARCHAR2(200),FECHAHORA DATE DEFAULT SYSDATE);



-- PREGUNTA 3 - AFIANZAMIENTO
-- 
-- Agregue las claves foráneas entre cliente–venta, venta–detalle y producto–detalle. Use nombres de restricciones con prefijo GIGH_.
-- SOLUCION:
ALTER TABLE GIGH_DETALLE_VENTA ADD CONSTRAINT FK_GIGH_DET_VENTA FOREIGN KEY(COD_VENTA) REFERENCES GIGH_VENTA;
ALTER TABLE GIGH_DETALLE_VENTA ADD CONSTRAINT FK_GIGH_DET_PRODUCTO FOREIGN KEY(COD_PRODUCTO) REFERENCES GIGH_PRODUCTOS;



-- PREGUNTA 4 - AFIANZAMIENTO
-- 
-- Ordene los DROP TABLE ... CASCADE CONSTRAINTS para eliminar el modelo completo sin errores de dependencia.
-- SOLUCION:
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GIGH_DETALLE_VENTA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GIGH_VENTA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END; /



-- PREGUNTA 5 - AFIANZAMIENTO
-- 
-- Construya un script idempotente que capture ORA-00942 al intentar eliminar una tabla inexistente y relance cualquier otro error.
-- SOLUCION:
BEGIN FOR t IN (SELECT 'GIGH_DETALLE_VENTA' n FROM DUAL UNION ALL SELECT 'GIGH_VENTA' FROM DUAL UNION ALL SELECT 'GIGH_PRODUCTOS' FROM DUAL UNION ALL SELECT 'GIGH_CLIENTE' FROM DUAL UNION ALL SELECT 'GIGH_LOG_VENTAS' FROM DUAL) LOOP BEGIN EXECUTE IMMEDIATE 'DROP TABLE '||t.n||' CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE!=-942 THEN RAISE; END IF; END; END LOOP; END; /



-- PREGUNTA 6 - AFIANZAMIENTO
-- 
-- Inserte un registro válido en cada tabla y compruebe con consultas que las claves y relaciones quedaron creadas.
-- SOLUCION:
INSERT INTO GIGH_CLIENTE VALUES(NULL,'ANA','PEREZ',NULL,'ANA.PEREZ@JUANISMARKET.CL');
INSERT INTO GIGH_PRODUCTOS VALUES(NULL,'PAN',500,900,10,10);
COMMIT;



-- PREGUNTA 7 - DESAFÍO
-- 
-- Desafío: agregue restricciones CHECK para precios, cantidades, stock y totales, y demuestre con una inserción inválida qué excepción produce Oracle.
-- SOLUCION:
ALTER TABLE GIGH_PRODUCTOS ADD CONSTRAINT CK_GIGH_PRECIOS CHECK(PRECIO_COMPRA>=0 AND PRECIO_VENTA>=0);
ALTER TABLE GIGH_PRODUCTOS ADD CONSTRAINT CK_GIGH_STOCK CHECK(STOCK>=0);



-- PREGUNTA 8 - DESAFÍO
-- 
-- Desafío: diseñe una versión del modelo que permita eliminar un cliente solo si no tiene ventas, explicando el efecto de la clave foránea.
-- SOLUCION:
DELETE FROM GIGH_CLIENTE WHERE COD_CLIENTE=:codigo AND NOT EXISTS(SELECT 1 FROM GIGH_VENTA WHERE COD_CLIENTE=:codigo);



-- PREGUNTA 9 - DESAFÍO
-- 
-- Desafío: escriba un bloque que consulte USER_CONSTRAINTS y USER_CONS_COLUMNS para listar las restricciones del modelo GIGH_.
-- SOLUCION:
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'GIGH%';



-- PREGUNTA 10 - DESAFÍO
-- 
-- Desafío: integre limpieza, creación, carga mínima y consultas de verificación en un único script ejecutable desde un esquema vacío.
-- 
-- SOLUCION:
-- Integrar los bloques 1 a 6 en este orden y terminar con SELECT * FROM cada tabla.



