/*
  ES2 - PROGRAMACIÓN PL/SQL
  Solución propuesta para el caso Juanita's Market
  Prefijo utilizado: CACB_
*/

SET SERVEROUTPUT ON;

/* ================================================================
   LIMPIEZA DEL ESQUEMA
   ================================================================ */
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CACB_DETALLE_VENTA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CACB_VENTA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CACB_PRODUCTOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CACB_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CACB_LOG_VENTAS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CACB_SEQ_CLIENTE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CACB_SEQ_PRODUCTO';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CACB_SEQ_LOG_VENTA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

/* ================================================================
   R1 - MODELO RELACIONAL
   ================================================================ */
CREATE TABLE CACB_CLIENTE(
  COD_CLIENTE       NUMBER,
  NOMBRE_CLIENTE    VARCHAR2(50) NOT NULL,
  APELLIDO1_CLIENTE VARCHAR2(50) NOT NULL,
  APELLIDO2_CLIENTE VARCHAR2(50),
  EMAIL_CLIENTE     VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_CACB_CLIENTE PRIMARY KEY (COD_CLIENTE),
  CONSTRAINT UQ_CACB_CLIENTE_EMAIL UNIQUE (EMAIL_CLIENTE)
);

CREATE TABLE CACB_PRODUCTOS(
  COD_PRODUCTO    NUMBER,
  NOMBRE_PRODUCTO VARCHAR2(50) NOT NULL,
  PRECIO_COMPRA   NUMBER(12,2) NOT NULL,
  PRECIO_VENTA    NUMBER(12,2) NOT NULL,
  CANTIDAD        NUMBER DEFAULT 0 NOT NULL,
  STOCK           NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT PK_CACB_PRODUCTOS PRIMARY KEY (COD_PRODUCTO),
  CONSTRAINT CK_CACB_PRODUCTOS_PRECIOS
    CHECK (PRECIO_COMPRA >= 0 AND PRECIO_VENTA >= 0),
  CONSTRAINT CK_CACB_PRODUCTOS_CANTIDAD CHECK (CANTIDAD >= 0),
  CONSTRAINT CK_CACB_PRODUCTOS_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE CACB_VENTA(
  COD_VENTA    NUMBER,
  FECHA_VENTA  DATE DEFAULT SYSDATE NOT NULL,
  TOTAL_VENTA  NUMBER(12,2) DEFAULT 0 NOT NULL,
  COD_CLIENTE  NUMBER NOT NULL,
  CONSTRAINT PK_CACB_VENTA PRIMARY KEY (COD_VENTA),
  CONSTRAINT FK_CACB_VENTA_CLIENTE
    FOREIGN KEY (COD_CLIENTE) REFERENCES CACB_CLIENTE(COD_CLIENTE)
);

CREATE TABLE CACB_DETALLE_VENTA(
  COD_VENTA    NUMBER,
  COD_PRODUCTO NUMBER,
  CANTIDAD     NUMBER NOT NULL,
  VALOR_TOTAL  NUMBER(12,2) NOT NULL,
  CONSTRAINT PK_CACB_DETALLE_VENTA PRIMARY KEY (COD_VENTA, COD_PRODUCTO),
  CONSTRAINT FK_CACB_DETALLE_VENTA_VENTA
    FOREIGN KEY (COD_VENTA) REFERENCES CACB_VENTA(COD_VENTA),
  CONSTRAINT FK_CACB_DETALLE_VENTA_PRODUCTO
    FOREIGN KEY (COD_PRODUCTO) REFERENCES CACB_PRODUCTOS(COD_PRODUCTO),
  CONSTRAINT CK_CACB_DETALLE_VENTA_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CK_CACB_DETALLE_VENTA_TOTAL CHECK (VALOR_TOTAL >= 0)
);

CREATE TABLE CACB_LOG_VENTAS(
  COD_LOG     NUMBER,
  INSTRUCCION VARCHAR2(50),
  DETALLE     VARCHAR2(200),
  FECHAHORA   DATE DEFAULT SYSDATE,
  CONSTRAINT PK_CACB_LOG_VENTAS PRIMARY KEY (COD_LOG)
);

/* ================================================================
   R2 - SECUENCIAS Y TRIGGERS AUTOINCREMENTALES
   ================================================================ */
CREATE SEQUENCE CACB_SEQ_CLIENTE
  START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE;

CREATE SEQUENCE CACB_SEQ_PRODUCTO
  START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE;

CREATE SEQUENCE CACB_SEQ_LOG_VENTA
  START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE;

CREATE OR REPLACE TRIGGER CACB_CLIENTE_AUTOINCREMENTAL
BEFORE INSERT ON CACB_CLIENTE
FOR EACH ROW
WHEN (NEW.COD_CLIENTE IS NULL)
BEGIN
  :NEW.COD_CLIENTE := CACB_SEQ_CLIENTE.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CACB_PRODUCTO_AUTOINCREMENTAL
BEFORE INSERT ON CACB_PRODUCTOS
FOR EACH ROW
WHEN (NEW.COD_PRODUCTO IS NULL)
BEGIN
  :NEW.COD_PRODUCTO := CACB_SEQ_PRODUCTO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CACB_LOG_AUTOINCREMENTAL
BEFORE INSERT ON CACB_LOG_VENTAS
FOR EACH ROW
WHEN (NEW.COD_LOG IS NULL)
BEGIN
  :NEW.COD_LOG := CACB_SEQ_LOG_VENTA.NEXTVAL;
END;
/

/* ================================================================
   R3 - TRIGGERS DE MAYÚSCULAS PARA CLIENTES Y PRODUCTOS
   ================================================================ */
CREATE OR REPLACE TRIGGER CACB_CLIENTE_MAYUSCULAS
BEFORE INSERT OR UPDATE ON CACB_CLIENTE
FOR EACH ROW
BEGIN
  :NEW.NOMBRE_CLIENTE    := UPPER(TRIM(:NEW.NOMBRE_CLIENTE));
  :NEW.APELLIDO1_CLIENTE := UPPER(TRIM(:NEW.APELLIDO1_CLIENTE));
  :NEW.APELLIDO2_CLIENTE := UPPER(TRIM(:NEW.APELLIDO2_CLIENTE));
  :NEW.EMAIL_CLIENTE     := UPPER(TRIM(:NEW.EMAIL_CLIENTE));
END;
/

CREATE OR REPLACE TRIGGER CACB_PRODUCTO_MAYUSCULAS
BEFORE INSERT OR UPDATE ON CACB_PRODUCTOS
FOR EACH ROW
BEGIN
  :NEW.NOMBRE_PRODUCTO := UPPER(TRIM(:NEW.NOMBRE_PRODUCTO));
END;
/

/* ================================================================
   R4 - TRIGGER RECTIFICADOR
   Si cambia COD_VENTA, actualiza sus detalles relacionados.
   ================================================================ */
CREATE OR REPLACE TRIGGER CACB_RECTIFICADOR
BEFORE UPDATE OF COD_VENTA ON CACB_VENTA
FOR EACH ROW
BEGIN
  UPDATE CACB_DETALLE_VENTA
     SET COD_VENTA = :NEW.COD_VENTA
   WHERE COD_VENTA = :OLD.COD_VENTA;
END;
/

/* ================================================================
   R5 - FUNCIÓN DE CORREO DEL CLIENTE
   Formato: NOMBRE.APELLIDO@JUANISMARKET.CL
   En duplicados agrega 1, 2, 3... antes de la arroba.
   ================================================================ */
CREATE OR REPLACE FUNCTION CACB_GENERA_EMAIL(
  NOMBRE_CLIENTE_P    IN CACB_CLIENTE.NOMBRE_CLIENTE%TYPE,
  APELLIDO1_CLIENTE_P IN CACB_CLIENTE.APELLIDO1_CLIENTE%TYPE
) RETURN CACB_CLIENTE.EMAIL_CLIENTE%TYPE
IS
  EMAIL_BASE CACB_CLIENTE.EMAIL_CLIENTE%TYPE;
  EMAIL_FINAL CACB_CLIENTE.EMAIL_CLIENTE%TYPE;
  SUFIJO NUMBER := 0;
  REPETIDOS NUMBER;
BEGIN
  EMAIL_BASE := UPPER(TRIM(NOMBRE_CLIENTE_P)) || '.' ||
                UPPER(TRIM(APELLIDO1_CLIENTE_P)) ||
                '@JUANISMARKET.CL';
  EMAIL_FINAL := EMAIL_BASE;

  LOOP
    SELECT COUNT(*)
      INTO REPETIDOS
      FROM CACB_CLIENTE
     WHERE EMAIL_CLIENTE = EMAIL_FINAL;

    EXIT WHEN REPETIDOS = 0;
    SUFIJO := SUFIJO + 1;
    EMAIL_FINAL := UPPER(TRIM(NOMBRE_CLIENTE_P)) || '.' ||
                   UPPER(TRIM(APELLIDO1_CLIENTE_P)) ||
                   TO_CHAR(SUFIJO) || '@JUANISMARKET.CL';
  END LOOP;

  RETURN EMAIL_FINAL;
EXCEPTION
  WHEN VALUE_ERROR THEN
    RAISE_APPLICATION_ERROR(-20001, 'DATOS INVÁLIDOS PARA EL CORREO');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002,
      'ERROR AL GENERAR CORREO ' || SQLCODE || ': ' || SQLERRM);
END;
/

/* ================================================================
   R6 - PROCEDIMIENTO INTEGRAL PARA PRODUCTOS (R/U/D)
   ================================================================ */
CREATE OR REPLACE PROCEDURE CACB_PRODUCTOS_RUD(
  OPCION_P         IN VARCHAR2,
  COD_PRODUCTO_P   IN CACB_PRODUCTOS.COD_PRODUCTO%TYPE DEFAULT NULL,
  NOMBRE_PRODUCTO_P IN CACB_PRODUCTOS.NOMBRE_PRODUCTO%TYPE DEFAULT NULL,
  PRECIO_COMPRA_P  IN CACB_PRODUCTOS.PRECIO_COMPRA%TYPE DEFAULT NULL,
  PRECIO_VENTA_P   IN CACB_PRODUCTOS.PRECIO_VENTA%TYPE DEFAULT NULL,
  CANTIDAD_P       IN CACB_PRODUCTOS.CANTIDAD%TYPE DEFAULT NULL,
  STOCK_P          IN CACB_PRODUCTOS.STOCK%TYPE DEFAULT NULL
) IS
  OPCION_LOCAL VARCHAR2(1) := UPPER(TRIM(OPCION_P));
BEGIN
  LOCK TABLE CACB_PRODUCTOS IN ROW EXCLUSIVE MODE;

  IF OPCION_LOCAL = 'R' THEN
    INSERT INTO CACB_PRODUCTOS(
      COD_PRODUCTO, NOMBRE_PRODUCTO, PRECIO_COMPRA,
      PRECIO_VENTA, CANTIDAD, STOCK)
    VALUES (
      COD_PRODUCTO_P, NOMBRE_PRODUCTO_P, PRECIO_COMPRA_P,
      PRECIO_VENTA_P, NVL(CANTIDAD_P, 0), NVL(STOCK_P, 0));

  ELSIF OPCION_LOCAL = 'U' THEN
    UPDATE CACB_PRODUCTOS
       SET PRECIO_COMPRA = PRECIO_COMPRA_P,
           PRECIO_VENTA  = PRECIO_VENTA_P,
           STOCK         = STOCK_P
     WHERE COD_PRODUCTO = COD_PRODUCTO_P;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20011, 'PRODUCTO NO ENCONTRADO');
    END IF;

  ELSIF OPCION_LOCAL = 'D' THEN
    DELETE FROM CACB_PRODUCTOS
     WHERE COD_PRODUCTO = COD_PRODUCTO_P;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20012, 'PRODUCTO NO ENCONTRADO');
    END IF;

  ELSE
    RAISE_APPLICATION_ERROR(-20013, 'OPCIÓN DEBE SER R, U O D');
  END IF;

  INSERT INTO CACB_LOG_VENTAS(INSTRUCCION, DETALLE)
  VALUES ('PRODUCTOS_' || OPCION_LOCAL,
          'COD_PRODUCTO=' || NVL(TO_CHAR(COD_PRODUCTO_P), 'AUTOMÁTICO'));
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20014, 'PRODUCTO DUPLICADO');
  WHEN VALUE_ERROR THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20015, 'VALOR INVÁLIDO EN PRODUCTO');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

/* ================================================================
   R7 - PROCEDIMIENTO DE INSERCIÓN PARA CLIENTES
   ================================================================ */
CREATE OR REPLACE PROCEDURE CACB_CARGA_CLIENTE(
  COD_CLIENTE_P       IN CACB_CLIENTE.COD_CLIENTE%TYPE DEFAULT NULL,
  NOMBRE_CLIENTE_P    IN CACB_CLIENTE.NOMBRE_CLIENTE%TYPE,
  APELLIDO1_CLIENTE_P IN CACB_CLIENTE.APELLIDO1_CLIENTE%TYPE,
  APELLIDO2_CLIENTE_P IN CACB_CLIENTE.APELLIDO2_CLIENTE%TYPE DEFAULT NULL,
  EMAIL_CLIENTE_P     IN CACB_CLIENTE.EMAIL_CLIENTE%TYPE DEFAULT NULL
) IS
  EMAIL_FINAL CACB_CLIENTE.EMAIL_CLIENTE%TYPE;
BEGIN
  LOCK TABLE CACB_CLIENTE IN ROW EXCLUSIVE MODE;

  IF EMAIL_CLIENTE_P IS NULL THEN
    EMAIL_FINAL := CACB_GENERA_EMAIL(NOMBRE_CLIENTE_P, APELLIDO1_CLIENTE_P);
  ELSE
    EMAIL_FINAL := EMAIL_CLIENTE_P;
  END IF;

  INSERT INTO CACB_CLIENTE(
    COD_CLIENTE, NOMBRE_CLIENTE, APELLIDO1_CLIENTE,
    APELLIDO2_CLIENTE, EMAIL_CLIENTE)
  VALUES (
    COD_CLIENTE_P, NOMBRE_CLIENTE_P, APELLIDO1_CLIENTE_P,
    APELLIDO2_CLIENTE_P, EMAIL_FINAL);

  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20021, 'CLIENTE O CORREO DUPLICADO');
  WHEN VALUE_ERROR THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20022, 'VALOR INVÁLIDO EN CLIENTE');
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

/* ================================================================
   R8 - PRUEBAS DE LOS REQUERIMIENTOS
   ================================================================ */
BEGIN
  CACB_CARGA_CLIENTE(NULL, 'Juanita', 'Pérez', 'Gómez');
  CACB_CARGA_CLIENTE(NULL, 'Juanita', 'Pérez', 'Gómez');

  CACB_PRODUCTOS_RUD('R', NULL, 'Leche', 800, 1200, 20, 20);
  CACB_PRODUCTOS_RUD('R', NULL, 'Pan', 500, 900, 30, 30);
  CACB_PRODUCTOS_RUD('U', 1, 'Leche', 850, 1300, 20, 18);

  INSERT INTO CACB_VENTA(COD_VENTA, COD_CLIENTE, TOTAL_VENTA)
  VALUES (5, 1, 1300);
  INSERT INTO CACB_DETALLE_VENTA(COD_VENTA, COD_PRODUCTO, CANTIDAD, VALOR_TOTAL)
  VALUES (5, 1, 1, 1300);
  UPDATE CACB_VENTA SET COD_VENTA = 6 WHERE COD_VENTA = 5;

  CACB_PRODUCTOS_RUD('D', 2);
END;
/

SELECT * FROM CACB_CLIENTE ORDER BY COD_CLIENTE;
SELECT * FROM CACB_PRODUCTOS ORDER BY COD_PRODUCTO;
SELECT * FROM CACB_VENTA ORDER BY COD_VENTA;
SELECT * FROM CACB_DETALLE_VENTA ORDER BY COD_VENTA, COD_PRODUCTO;
SELECT * FROM CACB_LOG_VENTAS ORDER BY COD_LOG;
