
  CREATE TABLE "OEHR_PRODUCT_INFORMATION" 
   (	"PRODUCT_ID" NUMBER(6,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 3520 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(50), 
	"PRODUCT_DESCRIPTION" VARCHAR2(2000), 
	"CATEGORY_ID" NUMBER(2,0), 
	"WEIGHT_CLASS" NUMBER(1,0), 
	"WARRANTY_PERIOD" INTERVAL YEAR (2) TO MONTH, 
	"SUPPLIER_ID" NUMBER(6,0), 
	"PRODUCT_STATUS" VARCHAR2(20), 
	"LIST_PRICE" NUMBER(8,2), 
	"MIN_PRICE" NUMBER(8,2), 
	"CATALOG_URL" VARCHAR2(50), 
	 CONSTRAINT "OEHR_PRODUCT_STATUS_LOV" CHECK (product_status in (  'orderable'
                                , 'planned'
                                , 'under development'
                                , 'obsolete')) ENABLE, 
	 CONSTRAINT "OEHR_PRODUCT_INFO_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "OEHR_PROD_SUPPLIER_IX" ON "OEHR_PRODUCT_INFORMATION" ("SUPPLIER_ID") 
  ;

   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."PRODUCT_ID" IS 'Primary key column.';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."PRODUCT_DESCRIPTION" IS 'Primary language description corresponding to translated_description in
oehr_product_descriptions, added to provide non-NLS text columns for OC views to access.';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."CATEGORY_ID" IS 'Low cardinality column, can be used for bitmap index. Schema SH uses it as foreign key';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."WEIGHT_CLASS" IS 'Low cardinality column, can be used for bitmap index.';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."WARRANTY_PERIOD" IS 'INTERVAL YEAER TO MONTH column, low cardinality, can be used for bitmap index.';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."SUPPLIER_ID" IS 'Offers possibility of extensions outside Common Schema.';
   COMMENT ON COLUMN "OEHR_PRODUCT_INFORMATION"."PRODUCT_STATUS" IS 'Check constraint. Appropriate for complex rules, such as "All products in 
status PRODUCTION must have at least one inventory entry." Also appropriate 
for a trigger auditing status change.';
   COMMENT ON TABLE "OEHR_PRODUCT_INFORMATION"  IS 'Non-industry-specific data in various categories.';