
  CREATE TABLE "OEHR_PRODUCT_DESCRIPTIONS" 
   (	"PRODUCT_ID" NUMBER(6,0), 
	"LANGUAGE_ID" VARCHAR2(3), 
	"TRANSLATED_NAME" NVARCHAR2(50) CONSTRAINT "OEHR_TRANSLATED_NAME_NN" NOT NULL ENABLE, 
	"TRANSLATED_DESCRIPTION" NVARCHAR2(2000) CONSTRAINT "OEHR_TRANSLATED_DESC_NN" NOT NULL ENABLE, 
	 CONSTRAINT "OEHR_PROD_DESC_PK" PRIMARY KEY ("PRODUCT_ID", "LANGUAGE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "OEHR_PRODUCT_DESCRIPTIONS" ADD CONSTRAINT "OEHR_PD_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "OEHR_PRODUCT_INFORMATION" ("PRODUCT_ID") ENABLE;

  CREATE INDEX "OEHR_PROD_DESC_PROD_IX" ON "OEHR_PRODUCT_DESCRIPTIONS" ("PRODUCT_ID") 
  ;

  CREATE INDEX "OEHR_PROD_DESC_TRANSLATED_IX" ON "OEHR_PRODUCT_DESCRIPTIONS" ("TRANSLATED_NAME") 
  ;

   COMMENT ON COLUMN "OEHR_PRODUCT_DESCRIPTIONS"."PRODUCT_ID" IS 'Primary key column.';
   COMMENT ON COLUMN "OEHR_PRODUCT_DESCRIPTIONS"."LANGUAGE_ID" IS 'Primary key column.';
   COMMENT ON TABLE "OEHR_PRODUCT_DESCRIPTIONS"  IS 'Non-industry-specific design, allows selection of NLS-setting-specific data derived at runtime, for example using the products view.';