
  CREATE TABLE "OEHR_LOCATIONS" 
   (	"LOCATION_ID" NUMBER(4,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"STREET_ADDRESS" VARCHAR2(40), 
	"POSTAL_CODE" VARCHAR2(12), 
	"CITY" VARCHAR2(30) CONSTRAINT "OEHR_LOC_CITY_NN" NOT NULL ENABLE, 
	"STATE_PROVINCE" VARCHAR2(25), 
	"COUNTRY_ID" CHAR(2), 
	 CONSTRAINT "OEHR_LOC_ID_PK" PRIMARY KEY ("LOCATION_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "OEHR_LOCATIONS" ADD CONSTRAINT "OEHR_LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "OEHR_COUNTRIES" ("COUNTRY_ID") ENABLE;

  CREATE INDEX "OEHR_LOC_CITY_IX" ON "OEHR_LOCATIONS" ("CITY") 
  ;

  CREATE INDEX "OEHR_LOC_COUNTRY_IX" ON "OEHR_LOCATIONS" ("COUNTRY_ID") 
  ;

  CREATE INDEX "OEHR_LOC_STATE_PROVINCE_IX" ON "OEHR_LOCATIONS" ("STATE_PROVINCE") 
  ;

   COMMENT ON COLUMN "OEHR_LOCATIONS"."LOCATION_ID" IS 'Primary key of oehr_locations table';
   COMMENT ON COLUMN "OEHR_LOCATIONS"."STREET_ADDRESS" IS 'Street address of an office, warehouse, or production site of a company. Contains building number and street name';
   COMMENT ON COLUMN "OEHR_LOCATIONS"."POSTAL_CODE" IS 'Postal code of the location of an office, warehouse, or production site of a company. ';
   COMMENT ON COLUMN "OEHR_LOCATIONS"."CITY" IS 'A not null column that shows city where an office, warehouse, or production site of a company is located. ';
   COMMENT ON COLUMN "OEHR_LOCATIONS"."STATE_PROVINCE" IS 'State or Province where an office, warehouse, or production site of a company is located.';
   COMMENT ON COLUMN "OEHR_LOCATIONS"."COUNTRY_ID" IS 'Country where an office, warehouse, or production site of a company is located. Foreign key to country_id column of the oehr_countries table.';
   COMMENT ON TABLE "OEHR_LOCATIONS"  IS 'Locations table that contains specific address of a specific office,
warehouse, and/or production site of a company. Does not store addresses /
locations of customers. Contains 23 rows references with the
oehr_departments and oehr_countries tables. ';