
  CREATE TABLE "OEHR_REGIONS" 
   (	"REGION_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"REGION_NAME" VARCHAR2(25), 
	 CONSTRAINT "OEHR_REG_ID_PK" PRIMARY KEY ("REGION_ID")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "OEHR_REGIONS"."REGION_ID" IS 'Primary key of oehr_regions table.';
   COMMENT ON COLUMN "OEHR_REGIONS"."REGION_NAME" IS 'Names of regions. Locations are in the countries of these regions.';
   COMMENT ON TABLE "OEHR_REGIONS"  IS 'Regions table that contains region numbers and names. Contains 4 rows references with the oehr_Countries table.';