
  CREATE TABLE "OEHR_COUNTRIES" 
   (	"COUNTRY_ID" CHAR(2) CONSTRAINT "OEHR_COUNTRY_ID_NN" NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(40), 
	"REGION_ID" NUMBER, 
	 CONSTRAINT "OEHR_COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;

  ALTER TABLE "OEHR_COUNTRIES" ADD CONSTRAINT "OEHR_COUNTR_REG_FK" FOREIGN KEY ("REGION_ID")
	  REFERENCES "OEHR_REGIONS" ("REGION_ID") ENABLE;

  CREATE INDEX "OEHR_COUNTRY_REGION_IX" ON "OEHR_COUNTRIES" ("REGION_ID") 
  ;

   COMMENT ON COLUMN "OEHR_COUNTRIES"."COUNTRY_ID" IS 'Primary key of oehr_countries table.';
   COMMENT ON COLUMN "OEHR_COUNTRIES"."REGION_ID" IS 'Region ID for the country. Foreign key to region_id column in the oehr_departments table.';
   COMMENT ON TABLE "OEHR_COUNTRIES"  IS 'oehr_country table. Contains 25 rows. References with oehr_locations table.';