
  CREATE TABLE "OEHR_DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER(4,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9990 INCREMENT BY 10 START WITH 280 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DEPARTMENT_NAME" VARCHAR2(30) CONSTRAINT "OEHR_DEPT_NAME_NN" NOT NULL ENABLE, 
	"MANAGER_ID" NUMBER(6,0), 
	"LOCATION_ID" NUMBER(4,0), 
	 CONSTRAINT "OEHR_DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "OEHR_DEPARTMENTS" ADD CONSTRAINT "OEHR_DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "OEHR_LOCATIONS" ("LOCATION_ID") ENABLE;
  ALTER TABLE "OEHR_DEPARTMENTS" ADD CONSTRAINT "OEHR_DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "OEHR_EMPLOYEES" ("EMPLOYEE_ID") ENABLE;

  CREATE INDEX "OEHR_DEPT_LOCATION_IX" ON "OEHR_DEPARTMENTS" ("LOCATION_ID") 
  ;

  CREATE INDEX "OEHR_DEPT_MANAGER_IX" ON "OEHR_DEPARTMENTS" ("MANAGER_ID") 
  ;

   COMMENT ON COLUMN "OEHR_DEPARTMENTS"."DEPARTMENT_ID" IS 'Primary key column of oehr_departments table.';
   COMMENT ON COLUMN "OEHR_DEPARTMENTS"."DEPARTMENT_NAME" IS 'A not null column that shows name of a department. Administration, Marketing, Purchasing, 
Human Resources, Shipping, IT, Executive, Public Relations, Sales, Finance, and Accounting. ';
   COMMENT ON COLUMN "OEHR_DEPARTMENTS"."MANAGER_ID" IS 'Manager_id of a department. Foreign key to employee_id column of oehr_employees table. 
The manager_id column of the oehr_employee table references this column.';
   COMMENT ON COLUMN "OEHR_DEPARTMENTS"."LOCATION_ID" IS 'Location id where a department is located. Foreign key to location_id column of oehr_locations table.';
   COMMENT ON TABLE "OEHR_DEPARTMENTS"  IS 'Departments table that shows details of departments where employees work. Contains 27 rows references with oehr_locations, oehr_employees, and oehr_job_history tables.';